### PR TITLE
try another way

### PR DESCRIPTION
**Pull request by mlubin**
Ref https://github.com/JuliaOpt/Ipopt.jl/pull/73

### CODE REVIEW

**Comment by mlubin** [comment]
@tkelman, this is a less hacky approach but means that we have to make these travis changes for all packages that build ipopt in their tests.

**Comment by mlubin** [comment]
(Accidentally deleted my comment while fighting with @coveralls)
@tkelman this is a less hacky approach but means that we have to use these travis settings on all packages that build Ipopt in their tests.

**Comment by mlubin** [comment]
CC @ccoffrin

**Comment by tkelman** [comment]
how about apt-get upgrading ca-certificates?

**Comment by mlubin** [comment]
@tkelman, can you do that without sudo?

**Comment by tkelman** [comment]
It might be in the apt packages plugin whitelist, would have to check. Maybe just a mac-compatible version of the sed call would be simpler.

**Comment by mlubin** [comment]
@tkelman, I tried listing ``ca-certificates`` under ``apt_packages``, didn't fix anything.

**Comment by ccoffrin** [comment]
I have been using,

```
addons:
  apt_packages:
    - gfortran
    - liblapack-dev
    - libgmp-dev
    - libglpk-dev
```

Does this resolve the issue?

**Comment by mlubin** [comment]
Try reruning a travis build. I'd bet Ipopt won't build correctly with that
configuration anymore.

**Comment by ccoffrin** [comment]
You are correct, https://github.com/ccoffrin/j5-ipopt-test

**Comment by mlubin** [comment]
Closed by #75

**Pull request closed without merging**
