### PR TITLE
Configure Ipopt with -DNO_fpu_control on ARM

### PR DESCRIPTION
**Pull request by jgonzal13**
ref https://projects.coin-or.org/BuildTools/wiki/current-issues (says "On P-Series(ppc64)", but same compilation error)

### CODE REVIEW

**Comment by mlubin** [comment]
Cool, does this actually work on ARM now?

**Comment by jgonzal13** [comment]
Took a while to finish building, but yes `Pkg.test("Ipopt")` succeeded on an Odroid XU4 with this change.

**Comment by mlubin** [comment]
LGTM, i'll let @tkelman sign off also

**Comment by jgonzal13** [comment]
@tkelman did the typing here while at @jgonzal13's computer

**Comment by mlubin** [comment]
That works then

**Comment by joehuchette** [comment]
Neat!

**Comment by jgonzal13** [comment]
We'd like to have this working easily for some other members of our lab, would it be okay to tag this quickly?

**Comment by mlubin** [comment]
Will do

**Comment by joehuchette** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/3825

**Comment by tkelman** [comment]
Just leaving a note that the ARM binaries of Julia are susceptible to `Provider BinDeps.BuildProcess failed to satisfy dependency libipopt` due to mismatched libstdc++ versions if Ipopt gets built by a newer version of `g++` than the ARM binaries were. Moving the copy of `lib/julia/libstdc++.so.6` that comes with in the Julia binaries out of the way seems to fix it.

**Pull request merged**
