### PR TITLE
RFC: MOI interface

### PR DESCRIPTION
**Pull request by mlubin**
TODO:
- [x] Linear constraints and objective
- [x] Quadratic constraints and objective
- [x] Duals
- [x] Fixed variables
- [x] Depend on tagged MOI release

### CODE REVIEW

**Comment by mlubin** [comment]
Now passing contlinear tests (with some documented exceptions). One cool thing about moving the processing of linear constraints into the wrappers is that we can do:
```julia
    if num_nlp_constraints == 0
        # TODO: this changes when we support quadratic
        addOption(m.inner, "jac_c_constant", "yes")
        addOption(m.inner, "jac_d_constant", "yes")
        addOption(m.inner, "hessian_constant", "yes")
    end
```
which saves the cost of evaluation callbacks when Ipopt is solving LPs.

**Comment by mlubin** [comment]
Ready to wrap this up soon, the remaining todos are minor.

**Comment by mlubin** [comment]
@blegat 0.7 was passing until recent changes. Could you take a peek? It's an error in MOIU: https://travis-ci.org/JuliaOpt/Ipopt.jl/jobs/367451714#L6386.

**Comment by odow** [comment]
Fixes are contained in this PR https://github.com/JuliaOpt/Ipopt.jl/pull/113

**Comment by blegat** [comment]
@mlubin This should have been fixed in https://github.com/JuliaOpt/MathOptInterface.jl/pull/316

**Pull request merged**
