### PR TITLE
adding mpb interface setparameters! 

### PR DESCRIPTION
**Pull request by jac0320**
make the slience/timelimit work universally

### CODE REVIEW

**Comment by tkelman** [comment]
Looks reasonable. Tests would be ideal.

**Comment by mlubin** [comment]
Here's an example test from Cbc: https://github.com/JuliaOpt/Cbc.jl/blob/59b815c07aa4165112743b6ebdbfc7095dfc8728/test/runtests.jl#L10

**Comment by jac0320** [comment]
* Modified one method of setparameters! given there are cases m.inner is not loaded
* Added tests

**Comment by jac0320** [comment]
The Ipopt `brand log` default cannot be silent. But as long as Ipopt is not restarted through command line (like AmplNLWriter->Bonmin calls Ipopt), the brand log will only shows up once.

**Comment by natschil** [comment]
This seems like it would have been a really useful pull-request, I'm now calling `push!(ipsol.options, (:print_level, 0))
` like it does as setparameters! is not available. However, as the pull-request was closed I'm now worried this could cause something to go wrong, what is the reason for closing the pull request?

**Comment by odow** [comment]
This is no longer relevant.

Use 
```Julia
model = Model(Ipopt.Optimizer)
set_silent(model)
# or
set_optimizer_attribute(model, "print_level", 0)
```

**Pull request closed without merging**
