### PR TITLE
add restoration phase options for MPB

### PR DESCRIPTION
**Pull request by odow**
Allows the user to set ``resto.[option]`` options. 

Not sure if there is a better/preferred way of handling things like this?

### CODE REVIEW

**Comment by mlubin** [comment]
LGTM

**Comment by IainNZ** [comment]
I'll tag a new version

**Comment by IainNZ** [comment]
Still awake @odow ?!

**Comment by odow** [comment]
I'm in Denmark at DTU until the end of July so its actually 5pm here right now

**Comment by IainNZ** [comment]
Oh ok, that makes more sense!

**Pull request merged**
