### PR TITLE
Fix depwarns on Julia 0.7 (bumps REQUIRE to 0.6)

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by mlubin** [comment]
Could you remove 0.5 on travis?

**Comment by mlubin** [comment]
Let's wait for https://github.com/JuliaLang/METADATA.jl/pull/11965 to go through, then bump MPB requirements here to get tests passing.

**Comment by mlubin** [comment]
MPB 0.7 is tagged, so just need to bump the upper bound to 0.8 here.

**Comment by timholy** [comment]
Seems like this is all set.

**Pull request merged**
